export const allDataQuery = (startDate: string, endDate: string) => `SELECT * 
FROM (
    SELECT DISTINCT 
        AWB.SEQ,
        AWB.DATE_CREATED AS FECHA_CREACION,
        AWB.PREFIX AS PREFIJO, 
        AWB.ISSUE_CARRIER AS CARRIER,
        AWB.SERIAL AS AWB, 
        AWB.ORIGIN AS ORIGEN, 
        AWB.DEST AS DESTINO,
        AWB.AGENT AS CODIGO_AGENTE, 
        FORWARDER.NAME AS NOMBRE_AGENTE,
        AWB.PIECES AS PIEZAS, 
        AWB_EXP.CHARGE_WEIGHT AS CWEIGHT,
        AWB.WEIGHT AS GROSSW,
        AWB.VOLUME AS VOLUMEN,
        AWB_IATA.RATE AS RATE,
        AWB_EXP.SELL_TOTAL AS FLETE,
        AWB_EXP.SELL_NET_NET AS SUBTOTAL,
        AWB_EXP.VAT_CARRIER AS TAX, 
        PAYMENT.ORIGINAL_AMOUNT AS TOTAL,
        AWB_EXP.SHIPPER AS CODIGO_CLIENTE,
        AWB.CARRIAGE_CURRENCY AS CURRENCY,
        AWB.PRICE_CLASS,
        AWB.SHC_LIST,
        AWB_EXP.CHARGE_CODE,
        AWB.CREATE_OPER
    FROM AWB 
    	LEFT JOIN PART FORWARDER ON FORWARDER.CODE = AWB.AGENT
    	LEFT JOIN AWB_EXP ON AWB.AWB_EXP_SEQ = AWB_EXP.SEQ 
    	LEFT JOIN AWB_IATA ON AWB_IATA.AWB_SEQ = AWB.SEQ 
    	LEFT JOIN PAYMENT ON PAYMENT.AWB_SEQ = AWB.SEQ
    	LEFT JOIN AWB_DIM ON AWB.SEQ = AWB_DIM.AWB_SEQ
    	LEFT JOIN AWB_EXP ON AWB.AWB_EXP_SEQ = AWB_EXP.SEQ 
    	LEFT JOIN PART SHIPPER ON SHIPPER.CODE = AWB_EXP.SHIPPER
    	LEFT JOIN AWB_FLT ON AWB_FLT.AWB_SEQ = AWB.SEQ
    	LEFT JOIN AWB_FLT_ACC ON AWB_FLT_ACC.AWB_SEQ = AWB.SEQ
    WHERE AWB.DATE_CREATED BETWEEN TO_DATE('${startDate}', 'YYYY-MM-DD') 
                              AND TO_DATE('${endDate}', 'YYYY-MM-DD')
)
ORDER BY FECHA_CREACION DESC;`;

export const fsuDataQuery = (startDate: string, endDate: string) => `SELECT *
FROM (
  SELECT 
    AWB.SERIAL AS AWB,
    AWB_FSU.OPER,
    AWB_FSU.TIME_STAMP,
    AWB_FSU.STATUS,
    AWB_FSU.ISSUE_CODE,
    AWB_FSU.FLIGHT_NUMBER,
    AWB_FSU.FLIGHT_DATE,
    AWB_FSU.ORIGIN,
    AWB_FSU.DEST,
    AWB.SEQ
  FROM AWB
  LEFT JOIN AWB_FSU ON AWB_FSU.AWB_SEQ = AWB.SEQ
  WHERE AWB_FSU.TIME_STAMP BETWEEN 
        TO_DATE('${startDate} 00:00:00','YYYY-MM-DD HH24:MI:SS')
    AND TO_DATE('${endDate} 23:59:59','YYYY-MM-DD HH24:MI:SS')
    AND AWB_FSU.ISSUE_CODE IN ('FSU', 'BKD', 'ADD')
)
ORDER BY SEQ DESC;`;
